name: Publish

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Cache Nodejs modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - name: Testing
      run: |
        npm run test:coverage
      env:
        CI: true
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Cache Nodejs modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - name: Publish
      run: |
        npm ci
        echo "dry-run npm publish"
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Merge develop into master
      run: |
        git merge develop
